# 以下内容会覆盖application.yml，即：application.yml配置以下内容是不会生效的
# 如果想要覆盖以下内容需要在dev、test、pre、pro中进行重新配置
spring:
  quartz:
    properties:
      org.quartz:
        scheduler:
          instanceName: QuartzScheduler
          instanceId: AUTO
        threadPool:
          threadsInheritContextClassLoaderOfInitializingThread: true
          class: org.quartz.simpl.SimpleThreadPool
          threadPriority: 5
          threadCount: 50
